"""Prepared starter questions for the chat.

Two sources, combined:
  * Template questions  - derived deterministically from catalog facets
    (categories + recurring attribute keywords). Free, always available.
  * LLM questions       - generated by Mistral from a catalog summary and
    CACHED in the settings table. Generated only when the catalog changes
    (called at the end of a sync), never on a per-chat request, so cost stays
    low. This matches the "LLM + templates" approach.
"""

from sqlalchemy.orm import Session
from sqlalchemy import func
from app.models.product import Product
from app.services.settings_service import SettingsService
from app.services.mistral import MistralService, ChatMessage
from datetime import datetime, timezone
from typing import List, Dict, Any, Optional
import logging
import json
import re

logger = logging.getLogger(__name__)

SUGGESTIONS_CATEGORY = "suggestions"

# German colour/material words that must be capitalized when they appear as a
# standalone noun (e.g. "zu Anthrazit", "Edelstahl oder Anthrazit"). The LLM
# often lower-cases them. Word boundaries mean an inflected ADJECTIVE ("weiße
# Klingel", "anthrazitgrau") is left untouched — only the bare noun form is hit.
_COLOR_MATERIAL_NOUNS = [
    "anthrazit", "edelstahl", "eisenglimmer", "aluminium", "messing", "kupfer",
    "weiß", "schwarz", "grau", "braun", "silber", "gold", "warmweiß", "kaltweiß",
]
_COLOR_RE = re.compile(r"\b(" + "|".join(_COLOR_MATERIAL_NOUNS) + r")\b", re.IGNORECASE)


def _normalize_de(text: str) -> str:
    """Capitalize standalone colour/material nouns the LLM lower-cased."""
    if not text:
        return text
    return _COLOR_RE.sub(lambda m: m.group(1)[0].upper() + m.group(1)[1:], text)

# Attribute keywords to look for when building template questions.
TEMPLATE_KEYWORDS = ["LED", "Gravur", "Funkklingel", "Anthrazit", "Fingerprint", "Edelstahl"]

# The shop's main PRODUCT families, in the order we want starter chips to appear.
# Used to (a) feed the LLM a representative set of categories — not the arbitrary
# first-8 — and (b) build the default chips one-per-family so they span the
# catalog instead of collapsing onto a single category (e.g. all Türklingeln).
# Only those actually present in the catalog are used.
MAIN_CATEGORIES = [
    "Türklingeln", "Briefkästen", "Sprechanlagen", "Paketboxen",
    "Hausnummern", "Außenleuchten", "Mülltonnenboxen", "Sicherheitstechnik",
]

# Keywords that map a free-text starter question to a main family, so the
# default chips can be kept to one-per-family (structural diversity) even if the
# LLM skews its global list toward one category.
FAMILY_KEYWORDS = {
    # NB: no "fingerprint" — it spans doorbells/intercoms/security, so it would
    # misclassify a Sprechanlage/Sicherheit question as a doorbell.
    "Türklingeln": ["türklingel", "klingel", "funkklingel", "gong", "klingeltaster"],
    "Briefkästen": ["briefkast", "briefkästen", "postkasten"],
    "Sprechanlagen": ["sprechanlage", "gegensprech", "intercom", "innenstation"],
    "Paketboxen": ["paketbox", "paket", "päckchen", "lieferung"],
    "Hausnummern": ["hausnummer"],
    "Außenleuchten": ["außenleuchte", "leuchte", "lampe", "beleucht", "strahler"],
    "Sicherheitstechnik": ["kamera", "alarm", "sensor", "sicherheit"],
    "Mülltonnenboxen": ["mülltonne", "müll"],
}


class SuggestionsService:
    def __init__(self, db: Session):
        self.db = db
        self.settings_service = SettingsService(db)

    # ---- Read (cheap, per request) -------------------------------------
    def get_suggestions(self, limit: int = 6, category: Optional[str] = None) -> List[str]:
        """Return cached LLM questions merged with templates.

        If `category` is given, prefer questions specific to that category
        (used by the storefront chat widget when viewing a category page).
        """
        if category:
            llm = self._get_cached_by_category().get(category, [])
            templates = self.build_template_suggestions(category)
            candidates = llm + templates
        else:
            candidates = self._diverse_default_suggestions(limit)

        merged: List[str] = []
        for q in candidates:
            q = _normalize_de((q or "").strip())
            if q and q not in merged:
                merged.append(q)
        return merged[:limit]

    @staticmethod
    def _family_of(question: str) -> Optional[str]:
        q = (question or "").lower()
        for family, kws in FAMILY_KEYWORDS.items():
            if any(kw in q for kw in kws):
                return family
        return None

    def _diverse_default_suggestions(self, limit: int) -> List[str]:
        """Default chips that always span categories.

        Take the (self-contained, natural) global LLM questions but keep at most
        ONE per product family, so the set can never collapse onto a single
        category. Any main family still unrepresented is filled with a template
        question, so the chips stay diverse even if the LLM skewed its output.
        """
        present = {
            row[0] for row in
            self.db.query(Product.category).distinct().filter(Product.category.isnot(None)).all()
        }
        chosen: List[str] = []
        overflow: List[str] = []          # extra same-family questions, used last
        seen_families = set()
        for q in self._get_cached_llm_questions():
            fam = self._family_of(q)
            if fam and fam not in seen_families:
                seen_families.add(fam)
                chosen.append(q)
            else:
                overflow.append(q)
        # Backfill missing families with a self-contained template question.
        for cat in MAIN_CATEGORIES:
            if len(chosen) >= limit:
                break
            if cat in present and cat not in seen_families:
                templ = self.build_template_suggestions(cat)
                if templ:
                    seen_families.add(cat)
                    chosen.append(templ[0])
        return chosen + overflow + self.build_template_suggestions()

    @staticmethod
    def _as_list(raw: Any) -> List[str]:
        # Settings.get_value() already json-decodes, so raw may be a list or str.
        if isinstance(raw, list):
            return [q for q in raw if isinstance(q, str) and q.strip()]
        if isinstance(raw, str) and raw:
            try:
                data = json.loads(raw)
                return data if isinstance(data, list) else []
            except Exception:
                return []
        return []

    def _get_cached_llm_questions(self) -> List[str]:
        raw = self.settings_service.get_category_settings(SUGGESTIONS_CATEGORY).get("llm_questions")
        return self._as_list(raw)

    def _get_cached_by_category(self) -> Dict[str, List[str]]:
        raw = self.settings_service.get_category_settings(SUGGESTIONS_CATEGORY).get("llm_by_category")
        if isinstance(raw, dict):
            return {k: self._as_list(v) for k, v in raw.items()}
        if isinstance(raw, str) and raw:
            try:
                data = json.loads(raw)
                return {k: self._as_list(v) for k, v in data.items()} if isinstance(data, dict) else {}
            except Exception:
                return {}
        return {}

    # ---- Templates (deterministic) -------------------------------------
    def _catalog_facets(self) -> Dict[str, Any]:
        categories = [
            row[0] for row in
            self.db.query(Product.category).distinct().filter(Product.category.isnot(None)).all()
        ]
        prices = [p for (p,) in self.db.query(Product.price).filter(Product.price.isnot(None)).all()]
        blob = " ".join(
            f"{n or ''} {d or ''}" for n, d in
            self.db.query(Product.name, Product.description).all()
        ).lower()
        keywords = [kw for kw in TEMPLATE_KEYWORDS if kw.lower() in blob]
        return {"categories": categories, "prices": prices, "keywords": keywords}

    def build_template_suggestions(self, category: Optional[str] = None) -> List[str]:
        facets = self._catalog_facets()
        out: List[str] = []
        # German templates; categories are German nouns — keep their casing
        # (lower-casing "Türklingeln" would be wrong German).
        # Natural, complete German questions (categories are plural/mass nouns,
        # so "Zeig mir alle …" / "Habt ihr …?" stay grammatical without needing
        # per-gender articles).
        if category:
            out.append(f"Zeig mir alle {category}")
            if facets["keywords"]:
                out.append(f"Habt ihr {category} mit {facets['keywords'][0]}?")
            out.append(f"Was sind die günstigsten {category}?")
            return out
        for cat in facets["categories"][:3]:
            out.append(f"Zeig mir alle {cat}")
        if facets["keywords"]:
            kw = facets["keywords"][0]
            cat = facets["categories"][0] if facets["categories"] else "Produkte"
            out.append(f"Habt ihr {cat} mit {kw}?")
        return out

    # ---- LLM generation (cached; called after a sync) ------------------
    def generate_llm_suggestions(self, count: int = 6, per_category: int = 3) -> Dict[str, Any]:
        """Ask Mistral for starter questions (global + per category) in ONE call.

        Results are cached in the settings table so per-chat requests never
        trigger an LLM call. Returns {'global': [...], 'by_category': {...}}.
        """
        facets = self._catalog_facets()
        if not facets["categories"]:
            return {"global": [], "by_category": {}}

        mistral_settings = self.settings_service.get_category_settings("mistral")
        api_key = mistral_settings.get("api_key")
        if not api_key:
            logger.info("Skipping LLM suggestions: no Mistral API key configured")
            return {"global": [], "by_category": {}}
        model = mistral_settings.get("model", "mistral-medium-latest")

        price_hint = ""
        if facets["prices"]:
            price_hint = (f"Preise liegen etwa zwischen {int(min(facets['prices']))} € "
                          f"und {int(max(facets['prices']))} €.")

        # Feed the LLM the MAIN product families first (not the arbitrary first-8
        # DB categories, which were all doorbell/accessory categories and left
        # the chips doorbell-only), then any others up to the cap.
        present = facets["categories"]
        present_set = set(present)
        main = [c for c in MAIN_CATEGORIES if c in present_set]
        others = [c for c in present if c not in main]
        cats = (main + others)[:8]

        system_prompt = (
            "Du bist deutschsprachiger E-Commerce-Texter für einen Shop mit Türklingeln, "
            "Briefkästen, Sprechanlagen, Paketboxen, Hausnummern und Außenleuchten aus "
            "Edelstahl. Du schreibst Start-Fragen, die ein Kunde im Produktberater-Chat "
            "anklickt.\n\n"
            "Antworte NUR mit einem JSON-Objekt exakt dieser Form: "
            '{"global": ["..."], "by_category": {"<Kategorie>": ["..."]}}.\n'
            f'"global": genau {count} Fragen, JEDE zu einer ANDEREN Produktkategorie aus '
            "der Liste (z. B. eine zu Türklingeln, eine zu Briefkästen, eine zu "
            "Sprechanlagen, eine zu Paketboxen, eine zu Hausnummern). Niemals alle zur "
            "gleichen Kategorie.\n"
            f'"by_category": ein Schlüssel pro genannter Kategorie (Kategoriename WORTWÖRTLICH '
            f"als Schlüssel), je {per_category} Fragen speziell zu DIESER Kategorie.\n\n"
            "WICHTIG – Sprache und Stil:\n"
            "- Muttersprachliches, natürliches, idiomatisches Deutsch. Jede Frage muss klingen, "
            "wie ein echter deutscher Kunde sie stellen würde.\n"
            "- Vollständige, flüssige Fragen — KEINE telegramm-artigen Fragmente, keine "
            "wörtlichen Übersetzungen, keine falsche Wortstellung.\n"
            "- Informelles Du. Korrekte Grammatik, Artikel und Groß-/Kleinschreibung.\n"
            "- Gut: 'Habt ihr eine Sprechanlage mit integrierter Kamera?', 'Welcher Briefkasten "
            "hat ein Zeitungsfach?', 'Gibt es Paketboxen für große Pakete?'.\n"
            "- Schlecht (NICHT so): 'Mit Kamera integriert?', 'Für Gewerbe oder Privat?', "
            "'Für mehrere Lieferungen?', 'Welche Größe passt?'.\n"
            "- Höchstens ~12 Wörter, aber lieber natürlich und vollständig als knapp und holprig. "
            "Keine Nummerierung."
        )
        user_prompt = (
            f"Kategorien: {', '.join(cats)}. "
            f"Häufige Merkmale: {', '.join(facets['keywords']) or 'n/a'}. {price_hint} "
            "Schreibe alle Fragen auf Deutsch (de-DE). Preise im Format 1.234,56 €."
        )

        try:
            mistral = MistralService(api_key=api_key)
            mistral.model = model
            content = mistral.chat_content(
                messages=[
                    ChatMessage(role="system", content=system_prompt),
                    ChatMessage(role="user", content=user_prompt),
                ],
                temperature=0.7,
                max_tokens=700,
                response_format={"type": "json_object"},
                model=model,
            )
            data = json.loads(content)
            global_qs = [_normalize_de(q.strip()) for q in data.get("global", [])
                         if isinstance(q, str) and q.strip()]
            by_cat_raw = data.get("by_category", {}) or {}
            by_cat = {
                str(k): [_normalize_de(q.strip()) for q in v if isinstance(q, str) and q.strip()]
                for k, v in by_cat_raw.items() if isinstance(v, list)
            }

            self.settings_service.set_setting(
                "llm_questions", json.dumps(global_qs), SUGGESTIONS_CATEGORY, encrypt=False
            )
            self.settings_service.set_setting(
                "llm_by_category", json.dumps(by_cat), SUGGESTIONS_CATEGORY, encrypt=False
            )
            self.settings_service.set_setting(
                "generated_at", datetime.now(timezone.utc).isoformat(),
                SUGGESTIONS_CATEGORY, encrypt=False
            )
            logger.info(
                f"Generated {len(global_qs)} global + "
                f"{sum(len(v) for v in by_cat.values())} per-category LLM questions"
            )
            return {"global": global_qs, "by_category": by_cat}
        except Exception as e:
            logger.error(f"LLM suggestion generation failed: {e}")
            return {"global": [], "by_category": {}}
