"""Prepared starter questions for the chat.

Two sources, combined:
  * Template questions  - derived deterministically from catalog facets
    (categories + recurring attribute keywords). Free, always available.
  * LLM questions       - generated by Mistral from a catalog summary and
    CACHED in the settings table. Generated only when the catalog changes
    (called at the end of a sync), never on a per-chat request, so cost stays
    low. This matches the "LLM + templates" approach.
"""

from sqlalchemy.orm import Session
from sqlalchemy import func
from app.models.product import Product
from app.services.settings_service import SettingsService
from app.services.mistral import MistralService, ChatMessage
from datetime import datetime, timezone
from typing import List, Dict, Any, Optional
import logging
import json

logger = logging.getLogger(__name__)

SUGGESTIONS_CATEGORY = "suggestions"

# Attribute keywords to look for when building template questions.
TEMPLATE_KEYWORDS = ["LED", "Gravur", "Funkklingel", "Anthrazit", "Fingerprint", "Edelstahl"]


class SuggestionsService:
    def __init__(self, db: Session):
        self.db = db
        self.settings_service = SettingsService(db)

    # ---- Read (cheap, per request) -------------------------------------
    def get_suggestions(self, limit: int = 6, category: Optional[str] = None) -> List[str]:
        """Return cached LLM questions merged with templates.

        If `category` is given, prefer questions specific to that category
        (used by the storefront chat widget when viewing a category page).
        """
        if category:
            llm = self._get_cached_by_category().get(category, [])
            templates = self.build_template_suggestions(category)
        else:
            llm = self._get_cached_llm_questions()
            templates = self.build_template_suggestions()

        merged: List[str] = []
        for q in llm + templates:
            q = (q or "").strip()
            if q and q not in merged:
                merged.append(q)
        return merged[:limit]

    @staticmethod
    def _as_list(raw: Any) -> List[str]:
        # Settings.get_value() already json-decodes, so raw may be a list or str.
        if isinstance(raw, list):
            return [q for q in raw if isinstance(q, str) and q.strip()]
        if isinstance(raw, str) and raw:
            try:
                data = json.loads(raw)
                return data if isinstance(data, list) else []
            except Exception:
                return []
        return []

    def _get_cached_llm_questions(self) -> List[str]:
        raw = self.settings_service.get_category_settings(SUGGESTIONS_CATEGORY).get("llm_questions")
        return self._as_list(raw)

    def _get_cached_by_category(self) -> Dict[str, List[str]]:
        raw = self.settings_service.get_category_settings(SUGGESTIONS_CATEGORY).get("llm_by_category")
        if isinstance(raw, dict):
            return {k: self._as_list(v) for k, v in raw.items()}
        if isinstance(raw, str) and raw:
            try:
                data = json.loads(raw)
                return {k: self._as_list(v) for k, v in data.items()} if isinstance(data, dict) else {}
            except Exception:
                return {}
        return {}

    # ---- Templates (deterministic) -------------------------------------
    def _catalog_facets(self) -> Dict[str, Any]:
        categories = [
            row[0] for row in
            self.db.query(Product.category).distinct().filter(Product.category.isnot(None)).all()
        ]
        prices = [p for (p,) in self.db.query(Product.price).filter(Product.price.isnot(None)).all()]
        blob = " ".join(
            f"{n or ''} {d or ''}" for n, d in
            self.db.query(Product.name, Product.description).all()
        ).lower()
        keywords = [kw for kw in TEMPLATE_KEYWORDS if kw.lower() in blob]
        return {"categories": categories, "prices": prices, "keywords": keywords}

    def build_template_suggestions(self, category: Optional[str] = None) -> List[str]:
        facets = self._catalog_facets()
        out: List[str] = []
        if category:
            out.append(f"Show me all {category.lower()}")
            if facets["keywords"]:
                out.append(f"{category} with {facets['keywords'][0]}")
            out.append(f"Cheapest {category.lower()}")
            return out
        for cat in facets["categories"][:3]:
            out.append(f"Show me {cat.lower()}")
        if facets["keywords"]:
            kw = facets["keywords"][0]
            cat = facets["categories"][0].lower() if facets["categories"] else "products"
            out.append(f"{cat.capitalize()} with {kw}")
        return out

    # ---- LLM generation (cached; called after a sync) ------------------
    def generate_llm_suggestions(self, count: int = 6, per_category: int = 3) -> Dict[str, Any]:
        """Ask Mistral for starter questions (global + per category) in ONE call.

        Results are cached in the settings table so per-chat requests never
        trigger an LLM call. Returns {'global': [...], 'by_category': {...}}.
        """
        facets = self._catalog_facets()
        if not facets["categories"]:
            return {"global": [], "by_category": {}}

        mistral_settings = self.settings_service.get_category_settings("mistral")
        api_key = mistral_settings.get("api_key")
        if not api_key:
            logger.info("Skipping LLM suggestions: no Mistral API key configured")
            return {"global": [], "by_category": {}}
        model = mistral_settings.get("model", "mistral-large-latest")

        price_hint = ""
        if facets["prices"]:
            price_hint = f"Prices range roughly €{int(min(facets['prices']))}-€{int(max(facets['prices']))}."

        # Cap categories in the prompt to keep it small.
        cats = facets["categories"][:8]

        system_prompt = (
            "You generate short starter questions a shopper might click in a product "
            "recommendation chat for a stainless-steel doorbell / mailbox / intercom store. "
            "Return ONLY a JSON object of exactly this shape: "
            '{"global": ["..."], "by_category": {"<Category>": ["..."]}}. '
            f'"global" has {count} questions covering different categories. '
            f'"by_category" has one key per provided category, each with {per_category} '
            "questions specific to THAT category. Each question under 9 words, natural, "
            "specific, no numbering."
        )
        user_prompt = (
            f"Categories: {', '.join(cats)}. "
            f"Common features: {', '.join(facets['keywords']) or 'n/a'}. {price_hint} "
            "Write all questions in English."
        )

        try:
            mistral = MistralService(api_key=api_key)
            mistral.model = model
            content = mistral.chat_content(
                messages=[
                    ChatMessage(role="system", content=system_prompt),
                    ChatMessage(role="user", content=user_prompt),
                ],
                temperature=0.7,
                max_tokens=700,
                response_format={"type": "json_object"},
                model=model,
            )
            data = json.loads(content)
            global_qs = [q.strip() for q in data.get("global", []) if isinstance(q, str) and q.strip()]
            by_cat_raw = data.get("by_category", {}) or {}
            by_cat = {
                str(k): [q.strip() for q in v if isinstance(q, str) and q.strip()]
                for k, v in by_cat_raw.items() if isinstance(v, list)
            }

            self.settings_service.set_setting(
                "llm_questions", json.dumps(global_qs), SUGGESTIONS_CATEGORY, encrypt=False
            )
            self.settings_service.set_setting(
                "llm_by_category", json.dumps(by_cat), SUGGESTIONS_CATEGORY, encrypt=False
            )
            self.settings_service.set_setting(
                "generated_at", datetime.now(timezone.utc).isoformat(),
                SUGGESTIONS_CATEGORY, encrypt=False
            )
            logger.info(
                f"Generated {len(global_qs)} global + "
                f"{sum(len(v) for v in by_cat.values())} per-category LLM questions"
            )
            return {"global": global_qs, "by_category": by_cat}
        except Exception as e:
            logger.error(f"LLM suggestion generation failed: {e}")
            return {"global": [], "by_category": {}}
